language: node_js
node_js:
  - lts/*
script: make test
env:
  global:
  - COMMIT_AUTHOR_NAME: "'Andago'"
  - COMMIT_AUTHOR_EMAIL: info.mango@gmail.com
  - LOCALES_PATH: package/_locales
deploy:
  provider: script
  script: bash ./deploy/chrome-extension-localization/deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- git submodule update --init --recursive
- openssl aes-256-cbc -K $encrypted_0cfb57c34e7b_key -iv $encrypted_0cfb57c34e7b_iv
  -in deploy/deploy_key.enc -out deploy/deploy_key -d
